In [16]:
import numpy as np

students = np.array([  [0.9,0.7,0.6],
                       [0.8,0.6,0.5],
                       [0.7,0.6,0.8]])

In [17]:
teachers = np.array( [ [0.6,0.8],
                       [0.9,0.7],
                       [0.7,0.9]])

In [18]:
scoring = students.dot(teachers)
scoring

array([[1.59, 1.75],
       [1.37, 1.51],
       [1.52, 1.7 ]])

In [6]:
scoring.sum(axis=0)

array([6.41, 6.39])

In [22]:
teacher1 = np.array( [1.2])

In [23]:
boost = students * teacher1
boost

array([[1.08, 0.84, 0.72],
       [0.96, 0.72, 0.6 ],
       [0.84, 0.72, 0.96]])

In [24]:
teacher_subject = np.array ( [1.2,1.3,1.1])

In [25]:
boost = students * teacher_subject
boost

array([[1.08, 0.91, 0.66],
       [0.96, 0.78, 0.55],
       [0.84, 0.78, 0.88]])